import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'es' | 'en' | 'pt' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Layout
    'nav.home': 'Inicio',
    'nav.profile': 'Mi Perfil',
    'nav.experience': 'Trayectoria',
    'nav.studio': 'Estudio Mágico',
    'nav.share': 'Compartir',
    'nav.logout': 'Cerrar Sesión',
    // Dashboard
    'dash.greeting': 'Hola, {name} 👋',
    'dash.subtitle': 'Aquí tienes un resumen del impacto de tu tarjeta digital.',
    'dash.visits': 'Visitas al Perfil',
    'dash.clicks': 'Clics en Contacto',
    'dash.shares': 'Veces Compartido',
    'dash.ready': '¿Listo para destacar?',
    'dash.readyDesc': 'Usa Nano Banana en el Estudio Mágico para generar un diseño único para tu tarjeta de presentación en segundos.',
    'dash.goStudio': 'Ir al Estudio Mágico',
    'dash.light': 'Claro (Formal)',
    'dash.dark': 'Oscuro (Elegante)',
    // Profile
    'profile.title': 'Mi Perfil',
    'profile.subtitle': 'Gestiona tu información personal y enlaces de contacto.',
    'profile.personalInfo': 'Información Personal',
    'profile.fullName': 'Nombre Completo',
    'profile.headline': 'Titular Profesional',
    'profile.headlinePlaceholder': 'Ej: Desarrollador Full Stack | Diseñador UX',
    'profile.bio': 'Biografía',
    'profile.bioPlaceholder': 'Escribe un breve resumen sobre ti...',
    'profile.contactLinks': 'Enlaces de Contacto',
    'profile.email': 'Correo Electrónico',
    'profile.phone': 'Teléfono',
    'profile.location': 'Ubicación',
    'profile.socialLinks': 'Redes Sociales',
    'profile.save': 'Guardar Cambios',
    'profile.saving': 'Guardando...',
    'profile.success': '¡Perfil actualizado con éxito!',
    'profile.photo': 'Foto de Perfil',
    'profile.uploadPhoto': 'Subir nueva foto',
    'profile.removePhoto': 'Quitar foto',
    // Experience
    'exp.title': 'Trayectoria',
    'exp.subtitle': 'Añade tu experiencia laboral, proyectos destacados y habilidades clave.',
    'exp.tab.exp': 'Experiencia',
    'exp.tab.proj': 'Proyectos',
    'exp.tab.skills': 'Habilidades',
    'exp.tab.cv': 'CV / Hoja de Vida',
    'exp.workExp': 'Experiencia Laboral',
    'exp.addExp': 'Añadir Experiencia',
    'exp.company': 'Empresa',
    'exp.role': 'Cargo',
    'exp.startDate': 'Fecha Inicio',
    'exp.endDate': 'Fecha Fin',
    'exp.location': 'Ubicación (Ciudad - País)',
    'exp.currentJob': 'Trabajo aquí actualmente',
    'exp.description': 'Descripción y Logros',
    'exp.cancel': 'Cancelar',
    'exp.save': 'Guardar',
    'exp.noExp': 'Sin experiencia',
    'exp.noExpDesc': 'Comienza añadiendo tu historial laboral.',
    'exp.present': 'Presente',
    'exp.projects': 'Proyectos Destacados',
    'exp.addProj': 'Añadir Proyecto',
    'exp.projName': 'Nombre del Proyecto',
    'exp.projRole': 'Tu Rol (Opcional)',
    'exp.projUrl': 'URL del Proyecto (Opcional)',
    'exp.projPhotos': 'Fotos del Proyecto (Máx 3)',
    'exp.uploadPhoto': 'Subir foto',
    'exp.noProj': 'Sin proyectos',
    'exp.noProjDesc': 'Añade los proyectos de los que estés más orgulloso.',
    'exp.skills': 'Habilidades',
    'exp.addSkill': 'Añadir Habilidad',
    'exp.skillName': 'Habilidad',
    'exp.skillCategory': 'Categoría',
    'exp.cat.tech': 'Técnica (Hard Skill)',
    'exp.cat.soft': 'Blanda (Soft Skill)',
    'exp.cat.tools': 'Herramientas / Software',
    'exp.noSkills': 'Sin habilidades',
    'exp.noSkillsDesc': 'Añade tus conocimientos técnicos y blandos.',
    'exp.certs': 'Certificados y Títulos',
    'exp.addCert': 'Añadir Documento',
    'exp.certName': 'Nombre del Certificado/Título',
    'exp.certIssuer': 'Institución Emisora',
    'exp.certDate': 'Fecha (Opcional)',
    'exp.certUrl': 'URL de Verificación (Opcional)',
    'exp.certImage': 'Imagen del Documento (Opcional)',
    'exp.noCerts': 'Sin certificados',
    'exp.noCertsDesc': 'Añade tus títulos y certificados para respaldar tus habilidades.',
    'exp.verify': 'Ver credencial',
    'exp.pdfOn': 'Descarga pública activada',
    'exp.pdfOff': 'Descarga pública desactivada',
    'exp.downloadPdf': 'Descargar PDF',
    // AI Assistant
    'ai.greeting': '¡Hola! Soy el asistente virtual de {name}. ¿En qué te puedo ayudar? Puedes preguntarme sobre su experiencia, habilidades o proyectos.',
    'ai.placeholder': 'Pregunta sobre mi perfil...',
    'ai.title': 'Asistente IA',
    'ai.error': 'Lo siento, hubo un error al conectar con el asistente. Por favor, inténtalo de nuevo más tarde.',
    'ai.fallback': 'este profesional',
    'ai.open': 'Abrir asistente IA',
    // Studio
    'studio.title': 'Estudio Mágico',
    'studio.subtitle': 'Diseña tu tarjeta con Nano Banana',
    'studio.describeCard': 'Describe tu tarjeta ideal',
    'studio.promptPlaceholder': 'Ej: Un diseño minimalista, oscuro, con acentos en azul eléctrico, ideal para un arquitecto de software.',
    'studio.presetMinimalist': '✨ Minimalista',
    'studio.presetNeon': '🚀 Neón Tech',
    'studio.presetCreative': '🎨 Creativo',
    'studio.presetCorporate': '🏛️ Corporativo',
    'studio.generating': 'Creando magia...',
    'studio.generateDesign': 'Generar Diseño',
    'studio.manualAdjustments': 'Ajustes Manuales',
    'studio.orientation': 'Orientación',
    'studio.horiz': 'Horiz',
    'studio.vert': 'Vert',
    'studio.alignment': 'Alineación',
    'studio.left': 'Izquierda',
    'studio.center': 'Centro',
    'studio.right': 'Derecha',
    'studio.typography': 'Tipografía',
    'studio.qrCode': 'Código QR',
    'studio.hideQR': 'Ocultar QR',
    'studio.showQR': 'Mostrar QR',
    'studio.background': 'Fondo',
    'studio.solidColor': 'Color Sólido',
    'studio.customImage': 'Imagen Personalizada',
    'studio.uploadImage': 'Subir imagen',
    'studio.saving': 'Guardando...',
    'studio.saved': '¡Guardado!',
    'studio.publishChanges': 'Publicar Cambios',
    'studio.publishDesign': 'Publicar Diseño',
    'studio.desktop': 'Desktop',
    'studio.mobile': 'Mobile',
    'studio.shareCard': 'Compartir tarjeta',
    'studio.scanQR': 'Escanea para ver mi perfil',
    'studio.call': 'Llamar',
    'studio.whatsapp': 'WhatsApp',
    'studio.sendEmail': 'Enviar correo',
    'studio.viewOnMap': 'Ver en el mapa',
    'studio.viewCV': 'Ver CV',
    'studio.myCV': 'Mi CV',
    'studio.website': 'Sitio Web',
    // Share
    'share.title': 'Compartir Perfil',
    'share.subtitle': 'Comparte tu tarjeta digital, portfolio o CV con el mundo.',
    'share.card': 'Tarjeta Digital',
    'share.cardDesc': 'Una micro web app pública que se ve exactamente como la tarjeta diseñada en el Estudio Mágico. Ideal para compartir rápidamente tu contacto en persona mediante el código QR.',
    'share.portfolio': 'Portfolio Completo',
    'share.portfolioDesc': 'Una página web moderna y responsiva con tu perfil, experiencia, proyectos y habilidades. Ideal para compartir en redes sociales o por correo.',
    'share.cv': 'CV Interactivo',
    'share.cvDesc': 'Un formato clásico de documento A4, listo para imprimir o descargar como PDF. Asegúrate de habilitar la descarga pública en la pestaña de CV.',
    'share.copy': 'Copiar Enlace',
    'share.copied': '¡Copiado!',
    'share.qr': 'Código QR',
    'share.downloadQr': 'Descargar QR',
    'share.scanQR': 'Escanea para ver la\nTarjeta Digital',
    'share.open': 'Abrir',
    // Login
    'login.title': 'Digital Card Pro',
    'login.subtitle': 'Tu identidad profesional en un solo lugar',
    'login.google': 'Continuar con Google',
    // Public
    'public.contact': 'Contactar',
    'public.portfolio': 'Ver Portfolio',
    'public.cv': 'Ver CV',
    'public.about': 'Sobre mí',
    'public.experience': 'Experiencia',
    'public.projects': 'Proyectos',
    'public.skills': 'Habilidades',
    'public.certs': 'Certificaciones',
  },
  en: {
    'nav.home': 'Home',
    'nav.profile': 'My Profile',
    'nav.experience': 'Experience',
    'nav.studio': 'Magic Studio',
    'nav.share': 'Share',
    'nav.logout': 'Sign Out',
    'dash.greeting': 'Hello, {name} 👋',
    'dash.subtitle': 'Here is a summary of your digital card\'s impact.',
    'dash.visits': 'Profile Visits',
    'dash.clicks': 'Contact Clicks',
    'dash.shares': 'Times Shared',
    'dash.ready': 'Ready to stand out?',
    'dash.readyDesc': 'Use Nano Banana in the Magic Studio to generate a unique design for your business card in seconds.',
    'dash.goStudio': 'Go to Magic Studio',
    'dash.light': 'Light (Formal)',
    'dash.dark': 'Dark (Elegant)',
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your personal information and contact links.',
    'profile.personalInfo': 'Personal Information',
    'profile.fullName': 'Full Name',
    'profile.headline': 'Professional Headline',
    'profile.headlinePlaceholder': 'Ex: Full Stack Developer | UX Designer',
    'profile.bio': 'Biography',
    'profile.bioPlaceholder': 'Write a short summary about yourself...',
    'profile.contactLinks': 'Contact Links',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.location': 'Location',
    'profile.socialLinks': 'Social Media',
    'profile.save': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.success': 'Profile updated successfully!',
    'profile.photo': 'Profile Photo',
    'profile.uploadPhoto': 'Upload new photo',
    'profile.removePhoto': 'Remove photo',
    'exp.title': 'Experience',
    'exp.subtitle': 'Add your work experience, featured projects, and key skills.',
    'exp.tab.exp': 'Experience',
    'exp.tab.proj': 'Projects',
    'exp.tab.skills': 'Skills',
    'exp.tab.cv': 'CV / Resume',
    'exp.workExp': 'Work Experience',
    'exp.addExp': 'Add Experience',
    'exp.company': 'Company',
    'exp.role': 'Role',
    'exp.startDate': 'Start Date',
    'exp.endDate': 'End Date',
    'exp.location': 'Location (City - Country)',
    'exp.currentJob': 'I currently work here',
    'exp.description': 'Description and Achievements',
    'exp.cancel': 'Cancel',
    'exp.save': 'Save',
    'exp.noExp': 'No experience',
    'exp.noExpDesc': 'Start by adding your work history.',
    'exp.present': 'Present',
    'exp.projects': 'Featured Projects',
    'exp.addProj': 'Add Project',
    'exp.projName': 'Project Name',
    'exp.projRole': 'Your Role (Optional)',
    'exp.projUrl': 'Project URL (Optional)',
    'exp.projPhotos': 'Project Photos (Max 3)',
    'exp.uploadPhoto': 'Upload photo',
    'exp.noProj': 'No projects',
    'exp.noProjDesc': 'Add the projects you are most proud of.',
    'exp.skills': 'Skills',
    'exp.addSkill': 'Add Skill',
    'exp.skillName': 'Skill',
    'exp.skillCategory': 'Category',
    'exp.cat.tech': 'Technical (Hard Skill)',
    'exp.cat.soft': 'Soft Skill',
    'exp.cat.tools': 'Tools / Software',
    'exp.noSkills': 'No skills',
    'exp.noSkillsDesc': 'Add your technical and soft skills.',
    'exp.certs': 'Certificates and Degrees',
    'exp.addCert': 'Add Document',
    'exp.certName': 'Certificate/Degree Name',
    'exp.certIssuer': 'Issuing Institution',
    'exp.certDate': 'Date (Optional)',
    'exp.certUrl': 'Verification URL (Optional)',
    'exp.certImage': 'Document Image (Optional)',
    'exp.noCerts': 'No certificates',
    'exp.noCertsDesc': 'Add your degrees and certificates to back up your skills.',
    'exp.verify': 'View credential',
    'exp.pdfOn': 'Public download enabled',
    'exp.pdfOff': 'Public download disabled',
    'exp.downloadPdf': 'Download PDF',
    // AI Assistant
    'ai.greeting': 'Hello! I am the virtual assistant for {name}. How can I help you? You can ask me about their experience, skills, or projects.',
    'ai.placeholder': 'Ask about my profile...',
    'ai.title': 'AI Assistant',
    'ai.error': 'Sorry, there was an error connecting to the assistant. Please try again later.',
    'ai.fallback': 'this professional',
    'ai.open': 'Open AI assistant',
    'studio.title': 'Magic Studio',
    'studio.subtitle': 'Design your card with Nano Banana',
    'studio.describeCard': 'Describe your ideal card',
    'studio.promptPlaceholder': 'Ex: A minimalist, dark design with electric blue accents, ideal for a software architect.',
    'studio.presetMinimalist': '✨ Minimalist',
    'studio.presetNeon': '🚀 Neon Tech',
    'studio.presetCreative': '🎨 Creative',
    'studio.presetCorporate': '🏛️ Corporate',
    'studio.generating': 'Creating magic...',
    'studio.generateDesign': 'Generate Design',
    'studio.manualAdjustments': 'Manual Adjustments',
    'studio.orientation': 'Orientation',
    'studio.horiz': 'Horiz',
    'studio.vert': 'Vert',
    'studio.alignment': 'Alignment',
    'studio.left': 'Left',
    'studio.center': 'Center',
    'studio.right': 'Right',
    'studio.typography': 'Typography',
    'studio.qrCode': 'QR Code',
    'studio.hideQR': 'Hide QR',
    'studio.showQR': 'Show QR',
    'studio.background': 'Background',
    'studio.solidColor': 'Solid Color',
    'studio.customImage': 'Custom Image',
    'studio.uploadImage': 'Upload image',
    'studio.saving': 'Saving...',
    'studio.saved': 'Saved!',
    'studio.publishChanges': 'Publish Changes',
    'studio.publishDesign': 'Publish Design',
    'studio.desktop': 'Desktop',
    'studio.mobile': 'Mobile',
    'studio.shareCard': 'Share card',
    'studio.scanQR': 'Scan to view my profile',
    'studio.call': 'Call',
    'studio.whatsapp': 'WhatsApp',
    'studio.sendEmail': 'Send email',
    'studio.viewOnMap': 'View on map',
    'studio.viewCV': 'View CV',
    'studio.myCV': 'My CV',
    'studio.website': 'Website',
    'share.title': 'Share Profile',
    'share.subtitle': 'Share your digital card, portfolio, or CV with the world.',
    'share.card': 'Digital Card',
    'share.cardDesc': 'A public micro web app that looks exactly like the card designed in the Magic Studio. Ideal for quickly sharing your contact in person via QR code.',
    'share.portfolio': 'Full Portfolio',
    'share.portfolioDesc': 'A modern and responsive web page with your profile, experience, projects, and skills. Ideal for sharing on social media or by email.',
    'share.cv': 'Interactive CV',
    'share.cvDesc': 'A classic A4 document format, ready to print or download as a PDF. Make sure to enable public download in the CV tab.',
    'share.copy': 'Copy Link',
    'share.copied': 'Copied!',
    'share.qr': 'QR Code',
    'share.downloadQr': 'Download QR',
    'share.scanQR': 'Scan to view\nDigital Card',
    'share.open': 'Open',
    'login.title': 'Digital Card Pro',
    'login.subtitle': 'Your professional identity in one place',
    'login.google': 'Continue with Google',
    'public.contact': 'Contact',
    'public.portfolio': 'View Portfolio',
    'public.cv': 'View CV',
    'public.about': 'About me',
    'public.experience': 'Experience',
    'public.projects': 'Projects',
    'public.skills': 'Skills',
    'public.certs': 'Certifications',
  },
  pt: {
    'nav.home': 'Início',
    'nav.profile': 'Meu Perfil',
    'nav.experience': 'Trajetória',
    'nav.studio': 'Estúdio Mágico',
    'nav.share': 'Compartilhar',
    'nav.logout': 'Sair',
    'dash.greeting': 'Olá, {name} 👋',
    'dash.subtitle': 'Aqui está um resumo do impacto do seu cartão digital.',
    'dash.visits': 'Visitas ao Perfil',
    'dash.clicks': 'Cliques em Contato',
    'dash.shares': 'Vezes Compartilhado',
    'dash.ready': 'Pronto para se destacar?',
    'dash.readyDesc': 'Use o Nano Banana no Estúdio Mágico para gerar um design único para o seu cartão de visita em segundos.',
    'dash.goStudio': 'Ir para o Estúdio Mágico',
    'dash.light': 'Claro (Formal)',
    'dash.dark': 'Escuro (Elegante)',
    'profile.title': 'Meu Perfil',
    'profile.subtitle': 'Gerencie suas informações pessoais e links de contato.',
    'profile.personalInfo': 'Informações Pessoais',
    'profile.fullName': 'Nome Completo',
    'profile.headline': 'Título Profissional',
    'profile.headlinePlaceholder': 'Ex: Desenvolvedor Full Stack | Designer UX',
    'profile.bio': 'Biografia',
    'profile.bioPlaceholder': 'Escreva um breve resumo sobre você...',
    'profile.contactLinks': 'Links de Contato',
    'profile.email': 'E-mail',
    'profile.phone': 'Telefone',
    'profile.location': 'Localização',
    'profile.socialLinks': 'Redes Sociais',
    'profile.save': 'Salvar Alterações',
    'profile.saving': 'Salvando...',
    'profile.success': 'Perfil atualizado com sucesso!',
    'profile.photo': 'Foto de Perfil',
    'profile.uploadPhoto': 'Enviar nova foto',
    'profile.removePhoto': 'Remover foto',
    'exp.title': 'Trajetória',
    'exp.subtitle': 'Adicione sua experiência de trabalho, projetos em destaque e habilidades principais.',
    'exp.tab.exp': 'Experiência',
    'exp.tab.proj': 'Projetos',
    'exp.tab.skills': 'Habilidades',
    'exp.tab.cv': 'CV / Currículo',
    'exp.workExp': 'Experiência de Trabalho',
    'exp.addExp': 'Adicionar Experiência',
    'exp.company': 'Empresa',
    'exp.role': 'Cargo',
    'exp.startDate': 'Data de Início',
    'exp.endDate': 'Data de Término',
    'exp.location': 'Localização (Cidade - País)',
    'exp.currentJob': 'Trabalho aqui atualmente',
    'exp.description': 'Descrição e Conquistas',
    'exp.cancel': 'Cancelar',
    'exp.save': 'Salvar',
    'exp.noExp': 'Sem experiência',
    'exp.noExpDesc': 'Comece adicionando seu histórico de trabalho.',
    'exp.present': 'Presente',
    'exp.projects': 'Projetos em Destaque',
    'exp.addProj': 'Adicionar Projeto',
    'exp.projName': 'Nome do Projeto',
    'exp.projRole': 'Seu Cargo (Opcional)',
    'exp.projUrl': 'URL do Projeto (Opcional)',
    'exp.projPhotos': 'Fotos do Projeto (Máx 3)',
    'exp.uploadPhoto': 'Enviar foto',
    'exp.noProj': 'Sem projetos',
    'exp.noProjDesc': 'Adicione os projetos dos quais você mais se orgulha.',
    'exp.skills': 'Habilidades',
    'exp.addSkill': 'Adicionar Habilidade',
    'exp.skillName': 'Habilidade',
    'exp.skillCategory': 'Categoria',
    'exp.cat.tech': 'Técnica (Hard Skill)',
    'exp.cat.soft': 'Interpessoal (Soft Skill)',
    'exp.cat.tools': 'Ferramentas / Software',
    'exp.noSkills': 'Sem habilidades',
    'exp.noSkillsDesc': 'Adicione suas habilidades técnicas e interpessoais.',
    'exp.certs': 'Certificados e Diplomas',
    'exp.addCert': 'Adicionar Documento',
    'exp.certName': 'Nome do Certificado/Diploma',
    'exp.certIssuer': 'Instituição Emissora',
    'exp.certDate': 'Data (Opcional)',
    'exp.certUrl': 'URL de Verificação (Opcional)',
    'exp.certImage': 'Imagem do Documento (Opcional)',
    'exp.noCerts': 'Sem certificados',
    'exp.noCertsDesc': 'Adicione seus diplomas e certificados para comprovar suas habilidades.',
    'exp.verify': 'Ver credencial',
    'exp.pdfOn': 'Download público ativado',
    'exp.pdfOff': 'Download público desativado',
    'exp.downloadPdf': 'Baixar PDF',
    // AI Assistant
    'ai.greeting': 'Olá! Sou o assistente virtual de {name}. Como posso ajudar? Você pode me perguntar sobre a experiência, habilidades ou projetos.',
    'ai.placeholder': 'Pergunte sobre o meu perfil...',
    'ai.title': 'Assistente de IA',
    'ai.error': 'Desculpe, ocorreu um erro ao conectar com o assistente. Por favor, tente novamente mais tarde.',
    'ai.fallback': 'este profissional',
    'ai.open': 'Abrir assistente de IA',
    'studio.title': 'Estúdio Mágico',
    'studio.subtitle': 'Crie seu cartão com Nano Banana',
    'studio.describeCard': 'Descreva seu cartão ideal',
    'studio.promptPlaceholder': 'Ex: Um design minimalista e escuro com detalhes em azul elétrico, ideal para um arquiteto de software.',
    'studio.presetMinimalist': '✨ Minimalista',
    'studio.presetNeon': '🚀 Neon Tech',
    'studio.presetCreative': '🎨 Criativo',
    'studio.presetCorporate': '🏛️ Corporativo',
    'studio.generating': 'Criando magia...',
    'studio.generateDesign': 'Gerar Design',
    'studio.manualAdjustments': 'Ajustes Manuais',
    'studio.orientation': 'Orientação',
    'studio.horiz': 'Horiz',
    'studio.vert': 'Vert',
    'studio.alignment': 'Alinhamento',
    'studio.left': 'Esquerda',
    'studio.center': 'Centro',
    'studio.right': 'Direita',
    'studio.typography': 'Tipografia',
    'studio.qrCode': 'Código QR',
    'studio.hideQR': 'Ocultar QR',
    'studio.showQR': 'Mostrar QR',
    'studio.background': 'Fundo',
    'studio.solidColor': 'Cor Sólida',
    'studio.customImage': 'Imagem Personalizada',
    'studio.uploadImage': 'Enviar imagem',
    'studio.saving': 'Salvando...',
    'studio.saved': 'Salvo!',
    'studio.publishChanges': 'Publicar Alterações',
    'studio.publishDesign': 'Publicar Design',
    'studio.desktop': 'Desktop',
    'studio.mobile': 'Mobile',
    'studio.shareCard': 'Compartilhar cartão',
    'studio.scanQR': 'Escaneie para ver meu perfil',
    'studio.call': 'Ligar',
    'studio.whatsapp': 'WhatsApp',
    'studio.sendEmail': 'Enviar e-mail',
    'studio.viewOnMap': 'Ver no mapa',
    'studio.viewCV': 'Ver CV',
    'studio.myCV': 'Meu CV',
    'studio.website': 'Site',
    'share.title': 'Compartilhar Perfil',
    'share.subtitle': 'Compartilhe seu cartão digital, portfólio ou CV com o mundo.',
    'share.card': 'Cartão Digital',
    'share.cardDesc': 'Um micro web app público que se parece exatamente com o cartão criado no Estúdio Mágico. Ideal para compartilhar rapidamente seu contato pessoalmente via código QR.',
    'share.portfolio': 'Portfólio Completo',
    'share.portfolioDesc': 'Uma página da web moderna e responsiva com seu perfil, experiência, projetos e habilidades. Ideal para compartilhar nas redes sociais ou por e-mail.',
    'share.cv': 'CV Interativo',
    'share.cvDesc': 'Um formato clássico de documento A4, pronto para imprimir ou baixar como PDF. Certifique-se de habilitar o download público na guia CV.',
    'share.copy': 'Copiar Link',
    'share.copied': 'Copiado!',
    'share.qr': 'Código QR',
    'share.downloadQr': 'Baixar QR',
    'share.scanQR': 'Escaneie para ver o\nCartão Digital',
    'share.open': 'Abrir',
    'login.title': 'Digital Card Pro',
    'login.subtitle': 'Sua identidade profissional em um só lugar',
    'login.google': 'Continuar com o Google',
    'public.contact': 'Contato',
    'public.portfolio': 'Ver Portfólio',
    'public.cv': 'Ver CV',
    'public.about': 'Sobre mim',
    'public.experience': 'Experiência',
    'public.projects': 'Projetos',
    'public.skills': 'Habilidades',
    'public.certs': 'Certificações',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.profile': 'Mon Profil',
    'nav.experience': 'Expérience',
    'nav.studio': 'Studio Magique',
    'nav.share': 'Partager',
    'nav.logout': 'Se Déconnecter',
    'dash.greeting': 'Bonjour, {name} 👋',
    'dash.subtitle': 'Voici un résumé de l\'impact de votre carte numérique.',
    'dash.visits': 'Visites du Profil',
    'dash.clicks': 'Clics de Contact',
    'dash.shares': 'Fois Partagé',
    'dash.ready': 'Prêt à vous démarquer ?',
    'dash.readyDesc': 'Utilisez Nano Banana dans le Studio Magique pour générer un design unique pour votre carte de visite en quelques secondes.',
    'dash.goStudio': 'Aller au Studio Magique',
    'dash.light': 'Clair (Formel)',
    'dash.dark': 'Sombre (Élégant)',
    'profile.title': 'Mon Profil',
    'profile.subtitle': 'Gérez vos informations personnelles et vos liens de contact.',
    'profile.personalInfo': 'Informations Personnelles',
    'profile.fullName': 'Nom Complet',
    'profile.headline': 'Titre Professionnel',
    'profile.headlinePlaceholder': 'Ex : Développeur Full Stack | Designer UX',
    'profile.bio': 'Biographie',
    'profile.bioPlaceholder': 'Écrivez un court résumé sur vous-même...',
    'profile.contactLinks': 'Liens de Contact',
    'profile.email': 'E-mail',
    'profile.phone': 'Téléphone',
    'profile.location': 'Emplacement',
    'profile.socialLinks': 'Réseaux Sociaux',
    'profile.save': 'Enregistrer',
    'profile.saving': 'Enregistrement...',
    'profile.success': 'Profil mis à jour avec succès !',
    'profile.photo': 'Photo de Profil',
    'profile.uploadPhoto': 'Télécharger une nouvelle photo',
    'profile.removePhoto': 'Supprimer la photo',
    'exp.title': 'Expérience',
    'exp.subtitle': 'Ajoutez votre expérience professionnelle, vos projets phares et vos compétences clés.',
    'exp.tab.exp': 'Expérience',
    'exp.tab.proj': 'Projets',
    'exp.tab.skills': 'Compétences',
    'exp.tab.cv': 'CV / Résumé',
    'exp.workExp': 'Expérience Professionnelle',
    'exp.addExp': 'Ajouter une Expérience',
    'exp.company': 'Entreprise',
    'exp.role': 'Rôle',
    'exp.startDate': 'Date de Début',
    'exp.endDate': 'Date de Fin',
    'exp.location': 'Emplacement (Ville - Pays)',
    'exp.currentJob': 'Je travaille actuellement ici',
    'exp.description': 'Description et Réalisations',
    'exp.cancel': 'Annuler',
    'exp.save': 'Enregistrer',
    'exp.noExp': 'Aucune expérience',
    'exp.noExpDesc': 'Commencez par ajouter votre historique professionnel.',
    'exp.present': 'Présent',
    'exp.projects': 'Projets Phares',
    'exp.addProj': 'Ajouter un Projet',
    'exp.projName': 'Nom du Projet',
    'exp.projRole': 'Votre Rôle (Optionnel)',
    'exp.projUrl': 'URL du Projet (Optionnel)',
    'exp.projPhotos': 'Photos du Projet (Max 3)',
    'exp.uploadPhoto': 'Télécharger une photo',
    'exp.noProj': 'Aucun projet',
    'exp.noProjDesc': 'Ajoutez les projets dont vous êtes le plus fier.',
    'exp.skills': 'Compétences',
    'exp.addSkill': 'Ajouter une Compétence',
    'exp.skillName': 'Compétence',
    'exp.skillCategory': 'Catégorie',
    'exp.cat.tech': 'Technique (Hard Skill)',
    'exp.cat.soft': 'Interpersonnelle (Soft Skill)',
    'exp.cat.tools': 'Outils / Logiciels',
    'exp.noSkills': 'Aucune compétence',
    'exp.noSkillsDesc': 'Ajoutez vos compétences techniques et interpersonnelles.',
    'exp.certs': 'Certificats et Diplômes',
    'exp.addCert': 'Ajouter un Document',
    'exp.certName': 'Nom du Certificat/Diplôme',
    'exp.certIssuer': 'Institution Émettrice',
    'exp.certDate': 'Date (Optionnel)',
    'exp.certUrl': 'URL de Vérification (Optionnel)',
    'exp.certImage': 'Image du Document (Optionnel)',
    'exp.noCerts': 'Aucun certificat',
    'exp.noCertsDesc': 'Ajoutez vos diplômes et certificats pour prouver vos compétences.',
    'exp.verify': 'Voir les informations d\'identification',
    'exp.pdfOn': 'Téléchargement public activé',
    'exp.pdfOff': 'Téléchargement public désactivé',
    'exp.downloadPdf': 'Télécharger le PDF',
    // AI Assistant
    'ai.greeting': 'Bonjour ! Je suis l\'assistant virtuel de {name}. Comment puis-je vous aider ? Vous pouvez me poser des questions sur son expérience, ses compétences ou ses projets.',
    'ai.placeholder': 'Posez une question sur mon profil...',
    'ai.title': 'Assistant IA',
    'ai.error': 'Désolé, une erreur s\'est produite lors de la connexion à l\'assistant. Veuillez réessayer plus tard.',
    'ai.fallback': 'ce professionnel',
    'ai.open': 'Ouvrir l\'assistant IA',
    'studio.title': 'Studio Magique',
    'studio.subtitle': 'Créez votre carte avec Nano Banana',
    'studio.describeCard': 'Décrivez votre carte idéale',
    'studio.promptPlaceholder': 'Ex : Un design minimaliste et sombre avec des accents bleu électrique, idéal pour un architecte logiciel.',
    'studio.presetMinimalist': '✨ Minimaliste',
    'studio.presetNeon': '🚀 Néon Tech',
    'studio.presetCreative': '🎨 Créatif',
    'studio.presetCorporate': '🏛️ Corporatif',
    'studio.generating': 'Création magique...',
    'studio.generateDesign': 'Générer le Design',
    'studio.manualAdjustments': 'Ajustements Manuels',
    'studio.orientation': 'Orientation',
    'studio.horiz': 'Horiz',
    'studio.vert': 'Vert',
    'studio.alignment': 'Alignement',
    'studio.left': 'Gauche',
    'studio.center': 'Centre',
    'studio.right': 'Droite',
    'studio.typography': 'Typographie',
    'studio.qrCode': 'Code QR',
    'studio.hideQR': 'Masquer le QR',
    'studio.showQR': 'Afficher le QR',
    'studio.background': 'Arrière-plan',
    'studio.solidColor': 'Couleur Unie',
    'studio.customImage': 'Image Personnalisée',
    'studio.uploadImage': 'Télécharger une image',
    'studio.saving': 'Enregistrement...',
    'studio.saved': 'Enregistré !',
    'studio.publishChanges': 'Publier les Modifications',
    'studio.publishDesign': 'Publier le Design',
    'studio.desktop': 'Bureau',
    'studio.mobile': 'Mobile',
    'studio.shareCard': 'Partager la carte',
    'studio.scanQR': 'Scannez pour voir mon profil',
    'studio.call': 'Appeler',
    'studio.whatsapp': 'WhatsApp',
    'studio.sendEmail': 'Envoyer un e-mail',
    'studio.viewOnMap': 'Voir sur la carte',
    'studio.viewCV': 'Voir le CV',
    'studio.myCV': 'Mon CV',
    'studio.website': 'Site Web',
    'share.title': 'Partager le Profil',
    'share.subtitle': 'Partagez votre carte numérique, votre portfolio ou votre CV avec le monde entier.',
    'share.card': 'Carte Numérique',
    'share.cardDesc': 'Une micro application web publique qui ressemble exactement à la carte conçue dans le Studio Magique. Idéal pour partager rapidement votre contact en personne via un code QR.',
    'share.portfolio': 'Portfolio Complet',
    'share.portfolioDesc': 'Une page web moderne et réactive avec votre profil, votre expérience, vos projets et vos compétences. Idéal pour partager sur les réseaux sociaux ou par e-mail.',
    'share.cv': 'CV Interactif',
    'share.cvDesc': 'Un format de document A4 classique, prêt à imprimer ou à télécharger au format PDF. Assurez-vous d\'activer le téléchargement public dans l\'onglet CV.',
    'share.copy': 'Copier le Lien',
    'share.copied': 'Copié !',
    'share.qr': 'Code QR',
    'share.downloadQr': 'Télécharger le QR',
    'share.scanQR': 'Scannez pour voir la\nCarte Numérique',
    'share.open': 'Ouvrir',
    'login.title': 'Digital Card Pro',
    'login.subtitle': 'Votre identité professionnelle en un seul endroit',
    'login.google': 'Continuer avec Google',
    'public.contact': 'Contact',
    'public.portfolio': 'Voir le Portfolio',
    'public.cv': 'Voir le CV',
    'public.about': 'À propos de moi',
    'public.experience': 'Expérience',
    'public.projects': 'Projets',
    'public.skills': 'Compétences',
    'public.certs': 'Certifications',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('language') as Language) || 'es';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string, params?: Record<string, string>) => {
    let text = translations[language]?.[key] || translations['es'][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, v);
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
